# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Aakash Maroti
title: Software Engineer (Computer Vision)
email: aakash.maroti@gmail.com
website: aakash94.github.io

# Social links
# twitter_username: facespics
github_username:  aakash94
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: aakashmaroti
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Wow. I am indecisive. Also I do not know what to put here.

  I am most skilled in: <mark>Memes</mark> and <mark>Sleeping</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Music
   - Football
   - Karting

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
